### PR TITLE
added blockchain download for faster sync

### PR DESCRIPTION
**Pull request by interbiznw**

### CODE REVIEW

**Comment by ch4ot1c** [comment]
lgtm - i think we should standardize the buckets and file link. `BTCPrivate/` or `BTCPrivate-Blockchain/`, and filename `[height]-[sync date].7z`

**Comment by interbiznw** [comment]
Not sure on the `[height]-[sync date].7z` as it seems like a good idea from a static standpoint and we would have to update the script every time there was a new file from a different height.

We were talking about scripting the copy+tar>upload procedure, so in that case if the filename was the same it would just get updated and overwritten every week.

**Comment by ch4ot1c** [comment]
Fair, so maybe btcpblockchain/blockchain.7z is always the latest, and old, prior ones are renamed height-syncdate.7z? Or, delete the priors?

**Comment by interbiznw** [comment]
@ch4ot1c yeah as you can see I changed to

`+wget https://storage.googleapis.com/btcpblockchain/blockchain.tar.gz`
`+tar -zxvf blockchain.tar.gz`

Then auto script can just overwrite blockchain.tar.gz every x amount of time, and correct me if I am wrong but I don't see a need to keep the old ones, on google storage at least.. The server could keep the previous one and name as `blockchain-height-syncdate.tar.gz` before it creates the new one to transfer to google cloud storage

**Pull request merged**
