### PR TITLE
v0.0.1

### PR DESCRIPTION
**Pull request by ch4ot1c**
Basic setup scripts for Bitcore:
- Fetching and building `btcpd` and `.zcash-params`
- Bitcore and store-demo installation
- Ubuntu environment setup

### CODE REVIEW

**Review by mattpass — CHANGES_REQUESTED** [review]
README.md - the Public AMI mentioned should actually be **btcp_store_demo (ami-97d7b7ef)**

**Review by daniel-farina — APPROVED** [review]
Thank you

**Comment by ch4ot1c** [comment]
BTCP-store-demo, `ami-90bbd4e8` is correct

**Comment by mattpass** [comment]
@ch4ot1c Ah, that wasn't there earlier, but is now. We should drop old one?

**Pull request merged**
